apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment-app
spec:  
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-app
    spec:       
      containers:
      - name: redis-container
        image: redis
        ports:
        - containerPort: 6379
          name: redis-port        