version: '3'
services:
  web:
    image: pbadhe34/my-apps:app1
    ports:
     - "5000:8090"
    networks:
      - appnet
  redis:
    image: "redis"
    networks:
      - appnet
networks:
   appnet:
